import re
import numpy as np
import random
MMicb="przeprzyktorwszydziewielszlajestsedzglowleczhrabkrzyrzekwiecdobrpowitadejakostartylkmnieprawwidzwojsstrzmlodpierniecmialczasstolmyslswiestrochocszczpanioczymowisopldruggdzidlugjednjeszstaltrzedzisziemgoscdawnmoskpotezosiniebprossiedbylotelikiedpatrswiajegosrodkoniznowpodkrzeckazdnaszterazaczklucdworzamkzwieslowchloksiekoncchcirekabronczestrzymozeogrodomuniedglosbedzbialnawerobagerwtakisercjeslustamilcludzsmiewiespostlitwksiastrajakbpolsbylaniemmieddalebiegwiedpiekmacirozmczarwlasalbozostmiespoznstandrogrecejakislucbardsobizgodcichdrzerozpdziwkropdostniespamirazegdybwlosrozkswojrejeszerrzucpochnierrodzwaszpodnniewzmiepewnrownkochmiejgrzezrobpanoroznbraczaramoglciagslonpanswolarykowolnniezskrzkrajledwmajowpadszukczekostapotrkrolwierdrzwslawaseschwisztucalewidasluzhorezawsgadazajapodopolotymcobrawszaporztegostadzabijedecalapiesniejbrzeramikilksprablysniktzwycrekezebyslyscharpowspomizdrozielwiatgestwtemspojbernchceruszcorapuszojczrzadksztokieniegtwarprocwzromojetylesiebtrawznajnigdwysznichpytawojnwiekczlozlotdotalaskgniecalypokonaglpanaskorwtenobrowoznsasinibyucielubigospgromzawodwocchrznaleniepwstatlumradzmusifranwiosdwiegoryznakjenewstrtychwszepolesmiarozsznalpalcstrupodajasnostrplacduszwkolraczblissporwnetkrokkoleszabdziawspospiepannzalozwrokobikrewpolanaprwziabylekrecrobirekustojdlonczerszpamajaznaczawiruchslyczycimiecskonglebnarozachtysizamespadbratwrzacesasciaokolpowonaposkrowznoosobglupwiwawodzskarscyzczolzabachybzwykspustylubogawyrzswoiwiemlatagotomarswyciwydakuchobieslugczulbylywracchmuzamiszkotabazolncztegodzwystwyrasposkrotgra"
PPrub="przewokuprzyktorpanijestmniepannmowiwiectylknawejedndziemyslizabwszyjakistarmozebarojeszrzecjegopowitakisobirzekbardczlochwimialkiedazebprawdobrludzwielalboskleniecodpawidzkobiglowjezedziszrobpanatysizaczrublkilkodpotegosposmiesczasbylogdybgdziznowszczdrugwlasbedzprosrobipierchocmoglniejoczymajaszlapodostawstactrzepatrstanniegrozmswojzawochcenaszignakochintespythrabkrzeciagpotepewntrzymusipokokazdsiebniespiekglospoworozupoznmlodochoszepdodasiedsmiepoczchciswiapienbylaleckpanuzycizostspojniepstropotrwiemswiejakbstraleczdopidrzwksiakupidziwpiecznajnaprparedaleteratychpracjakapomykamizobamiedtowawasoniezzapydomuprezsluzsprasercpanorekenaglchodnichzamiulicinnyswoiniebwydajedemiejparymojestoltwargodzzresnatuspokpansdrogplacodezwszetrocznalosobzawsglupslowtomamoznpostcalykonilistsprzstalusmizarawarszdawniedwysznigdrzucpytachlodostmilopamiszumdawndoktwrocprocdlacrozpspolczymrecechybfranwspoczeswiedadwookolkoncdlugzaslgoscpodawiermojauczumarupojetakapodntylerokuczegnastslysrazywystnajwwyraniewrekabylekrzywyglwiekmaszwieszapopolowtraposzoddasalotymcznaccztesweganizbedewziapowtpolinareojciziemgeiszatropuskupcsubizebystosdniazmiewidozdajwypajutrchorcoracaleogroduszbiedpochzachnalezakolokarownpietzaprrzadmogezastraczponimracostakazarodzfotespotflorcalawtedsamoobrawolnzadnsamezdziuwazczulzblizapeciotpozwmuszposahandustasluczabigniewpadcichgotorazijakonoweskonzapawychnimizamkinnewysosmiaksiespodnowywolaczekdrzemrukwydosamaczytlataotwoszespomiszerobieznampodlszyblepimilcwzrunazwruchciezmezcwyjedoroschouderjedzkolealezmincmocnraminieksadzzajemiecwst"
SSieb="przektorprzywinijestjegoligipoczjednleczrzekmniewieccezawszychwidziepetrmowimogltylkludzjeszbylowidzglowjakimozeswiarzympowiniewchrzmyslsobiczastegosmiechilodponiegpanioczytwarczymnawejakbalbobedzzyciterachrydomunerojeslpierszczniecstramiloglosmialniejpatrprawmiasjakochcitakistargdybniepduszwydadobrwidowielwiergdzibylamiedczlorozpkochsercwlaszarazostuczyaulupodnmiesslowwowcursutwojrzecznowpostswiepotechocrozkwiedkrzywresdaletygeogroniesnaststropotrpochnichpompchcepewndrogbogorozmspieniebstaljakaauguramiziemodrzapossiebwiekrowntychpodomusitlumwroccalywiesznalniezinnyzmieczynpoznpiekwszeczeskazdcieboddarozuslyssluckilkustaspoknaukmlodpiotdlatwiemrecedziswsrowolanadzpowtnaglsposcorasprapalapomyzamitymctakznaszpozawieztrzezdawmiejdrugznajbowidawncalezwrozapaswojniemchodgrecpozoczekzlotnigdakteproszabizachofiazwieszukkazaboskstanpytakrotbardcialdlugdotamojespytinneuciewrazznaczawomodlzatrglauslonwycizapoostrpretognipomonimiczulwolnujrzjededostwaszarenzolnmojapopppowodziwsiedostawyznkoniradobylymilcpozwrzucrazeciemgniemoznpoprgrozgdyzopuscalachorzawspiesdopimajaimieznakobieopowszalwpranoweistoczegtrzybramnaprpokozbliniedpodzzupewlossobaniktucztkolowspotobipojdzbytuwiemiecchcakobipamipelninniamfijutrsamaeuniwestotwomaszposawprozrozposlzadnnocysadztysiciagwzruogarwychdlonsluzspodzaslkrysplomchwyancjobecdlacwsparekerekarazimorzgrekzbrozalecyrkbedawyprrodzspojblaskoncodnazwykulicsamebogapowszaniokrzwobebialkamirozswyszwyslprocumiedosczwycmogepoloatrigotolektolbrmoganapepodaposzdniazreskrolskorstolzgubrozdwladwoliumiatobaczarkrwinierspotposiwia"

Micb=[MMicb[i:i+4] for i in range(0, len(MMicb), 4)]
Prub=[PPrub[i:i+4] for i in range(0, len(PPrub), 4)]
Sieb=[SSieb[i:i+4] for i in range(0, len(SSieb), 4)]

MMice="eizdmeikyzsweinahcynzcelcajaogeitsejeiwomelaeinmlkezoklyicsookajaibaaizdhcikjeinezczlizdeineceiwlyzclaizlaimeiboeicemetozaredezryzrpjeikainasazcyzcoogejlawoeibezezreinzycsyazsuzsuealaieinsiksjmesaolybcohclatsyzdeogencizdhceiywollankeicsaineeiwdeiksilsemiksumodyrotydeieicztewamezasizdhcyweiwtathceinoezrouwonldezcazdolokoktsezomceinlazrlazchcyteiwaybkaaicsmeineinwawolanoioblaezreladaybezawtsyzawecerogetlansewolyzrocazcmelianemcadizseiowtsezswarotkinzimaklawrizdoliwajelacahcakerazdelahcalybynoiilyzynorlyzrezkacawoynzoimeilaicozdreiktcyzccsonalawkaboaleiyzslhcinlazslalohcakwokyabeziklecazseleiyzcaalacdorseindumeiukmahcyrjezselgaikswybydezsaahcuakincadaynozlazaawarhcyzmeiclarezaicylaiejeikeiwilezmeiwlawaizdeyteiogulanyztkinekerileicezrzeicnedezaraacilydzacaiweinymetwanapogezeinlzcezmyzcelytcajuzaroadaleicahcazycilyzarywarleicareiandemelymehcdatoineilangamyzanozzeizazczerotilenybinotseydgihcatzdaieintyzsuytraythcimynecincatsalencsolaldaynyzylawjeichcowainoyzrtuknahcaiilzsiceiazreimaslainceizizduazdayroglyzseinkynawakleezrblicoiwzroksiliwoyzeiwonaechcdatsrosezdeimywohcycikzcalzslawyalatmewtjeromynzogereinicseitnejakzccorkadwaaisoynaiyratlinolsoialazicseigormeroigulilawilowecreyzrewokiucnoilatukdouinezreiogewmyzsikatwociateiazsayzraolaienzcciwatenwwokzmetsatsuycinsolgkanzwosanorbejowmezcilakimawejyzciwolgomonawdozrisonkemacsodhcylabosezsutlatukeryzelcakeylybalyzenozelaconozaladaksiynnaulyteinrmenojeigakcauinakazsisozeiklhcanalakelopynjoanloalkemetameloywomhcallineuzcotybzowoleicotaiwezceawezonaicazrhcadanarjewoajakajadakliiknamejalicsyzcemig"
PPrue="ikslogeitsejeizdeinminapeinamelaoklytewajeincajaeiboannahcynezomceiwicsoezczilezogenyrotogejogetybezyzswozdralebydeilaizaineainameikeinejeikoblaalaizezreiwoikceanapeicshcikkeiwlawolraplalsarotldezmeiwakswogeziliwuwoneiceaicseibelaimsizdlatyilbuolybdezrliwolkezcawoyzrpyceieinzalaweiwayzdeoktsmetshcytlazchceikandmeinlyzclyzrogeweinleinshcatnoralizdzareelgayzcocsonechcalenzsammetojewoejadlankzseiynozycanybydmyblerotmeliiwomizdoawoneiczneizynnaunapsazcumeimiksowtsalybymsiateieikazcelolawhcinilebaklilahcalyzybkaoreicajucizdikatlawybosoikcojelahcyrezrbiksrerapjeceatzslatsujokizdualiwezswezdamesamelyumodalatezkaynoimyzsjezsawolekeryzrohcakmyrohcywlaloalkeladaewolupelyzarladoyteinedesikaliboimananzoeinoogerijcahcioiwzrcahcimakehcojeroezsoawtsanozciboalalceiphcyzalazyratlaiclazrcohcukorimyntsailainmehciguryzrtuinelangaladejcacyzcydgieindhcaihcyceintabezcazdketamyzclazataiszciwlicaabyhydetecermikaakatceizycsyzeicmesoajomandezaraeicycaiwelaclgomlanplsymylacaicelawraindaliceinwakeialzslicozaicezaiikswyzceceicelytycinibormezaezrerotkeiktyblaeiwdedebyzcailsycsolceimajowcezralaccadaelsypelkolokomimjejoluzcynawilawisumeliwikajusazcazruinaadwaecinycajeiwizarojokoezsulawzybalileiicseadalmuabhcazilowejowabosegomeinnolaimenaeiksceinmynoogelydzaawosywollazsylaweipeanyzmalalanhuletzsancawyjeipnamuecajortusakaejomaklehcanmyndimaiuktasetsennamenozaweiminjendogemcazceteiceisylaiybcoakzseleiajamtaiwyciltsilimateizasolgynzcowaradaiacdaanoienzcogecajcaezroamasejeimanzakajlawaiknuaicyyzramiowwotnuiceamyzzelamynzmeimanibimasanzceicaikzcyzslymeiedwatakojezcaibawon"
SSiee="eizdogejeinatsejzcelzsujlkezhcynazsuyzsweinmzsuiogeimeiwezczoklyjeinyrotogeticsoeibozezrolybhciklaizainecajaeinelazcceiwarotmelaezomkandogenmeikiliweiwosazczareeibeyzrplaimmyzcilsetewaybkaaigierotumodhcyralaimeindezrcsoneicsliwoarazrazemezaeiczainaaicslgomyzrokeiwiigiyzcoogezzseiezkauineogereinzhcytcezrlizdeicealawybydizdulyzryzdemesalatsalyborenhcinlawoldezokajcawohcyceigihcaiolawhcywjeikwonzoktscsolceizaliwlsymjeromyrolaiclazaowtsylawyzslanoiawoleicyecincizdolihhceilyzceinoilawlatyjelaelgajececahcewolileilalswokidorszaroycinhcyzeinlyzsumetoogewecercazdcyzclazrlawyenozladaciwoeikametstsaizrawynozmyzsechcylaieimylicoeintatsasusriwozeikteliwetkaolaihcaksizdcreicseimuirjezcizdocsodlaloalkecatslahcywolasuteiksilyzalateindlazsmyblmyzrimynajowydgiimanaicyeinysunialenyzrailezcadaceinakualawaandealyzimalejownedeainoanzoalacilzsezrbdatoanolezswanozmelihcylmikailazicrealaziminmesocawylsoiezsuotsaatsucaiwcajuajomeinsluzctaiwhcazezraolatsutsimakycsyazraabezawtsjeizysolnajiceimwonaneizzdeiinniylybmehcezrezeinselazydgelacmynolotsrtoialzsalezeiwdeiwiwogoylacabosalgoakajmeicecrecazcusazonaworeiyconjendyzcelainecajjezsezdosolgsikaejeizsamtkinezrtylazoblaylezjokoumyzcyzronoimynzyzreuzsuhcanylyzamyzybcohciouinamylamunaoksimyndolizamasilowakinazczonozennihcacakerlanzywilicsekodiogecjeipaliceizalawrmujcolokzarwsakaekermynaaklialadanorilsyezroimeiyraiejomzsezcsezhcarmycameniatzsceboonaimelyeiwaegomisummezsiceicanzlaiwolzsyblaeinpcicsogelmywoogemeimiynorimaiiinolinyynoimikswiceuicyagoranilcohcedebumeijewoabotenzcisrebosowosuakatewoneiniimazejadezsaymeityb"

Mice=[MMice[i:i+4] for i in range(0, len(MMice), 4)]
Prue=[PPrue[i:i+4] for i in range(0, len(PPrue), 4)]
Siee=[SSiee[i:i+4] for i in range(0, len(SSiee), 4)]


def count(string, minLen,splitl):
    pattern = '[^A-Za-z0-9]+'
    validWordsB=[x.lower()[:splitl] for x in re.split(pattern, string) if len(x) >=minLen]
    validWordsE=[x.lower()[::-1][:splitl] for x in re.split(pattern, string) if len(x) >=minLen]

    bmic = 0
    bpru = 0
    bsie = 0

    emic = 0
    epru = 0
    esie = 0

    mic = 0
    pru = 0
    sie = 0

    A = 0.5
    B = 0.3


    for word in validWordsB:
        if (word in Micb):
            bmic += 1 
        if (word in Prub):
            bpru += 1 
        if (word in Sieb):
            bsie += 1 
    for word in validWordsE:
        if (word in Mice):
            emic += 1 
        if (word in Prue):
            epru += 1 
        if (word in Siee):
            esie += 1 

    mic += emic * B + bmic * A
    sie += esie * B + bsie* A
    pru += epru * B + bpru* A

    if mic == pru == sie:
        return random.randint(0,2)
    return np.argmax((mic, pru, sie))

makers = ["Mickiewicz","Prus","Sienkiewicz"]
T = int(input())
for i in range(T):
    frag = input()
    print(makers[count(frag,4,4)])
