#include <bits/stdc++.h>
#define pb push_back
typedef long long ll;
using namespace std;

// ile najczesciej
string Mic[300]={"lecz","jest","tylko","rzekl","jako","hrabia","sedzia","mnie","wiec","przy","jeszcze","przed","przez","wszyscy","tadeusz","gdzie","choc","bylo","wojski","potem","mial","oczy","jego","teraz","niech","domu","nawet","dzis","ktory","szlachta","znowu","kiedy","jesli","wszystko","moze","jakby","albo","gerwazy","rece","sobie","telimena","bedzie","razem","miedzy","glowy","ktora","reka","byla","glowe","bardzo","panie","klucznik","ziemi","robak","podkomorzy","tadeusza","zamku","widac","tymczasem","gdyby","krzyknal","tego","wszystkie","zawsze","cala","nikt","reke","zaraz","wtem","rzecz","rykow","coraz","jeden","ledwie","czas","siebie","strony","niej","stal","dlugo","nich","tyle","dotad","trzeba","chcial","ktore","wtenczas","wielki","przeciez","nigdy","gosci","pana","ksiadz","glowa","niby","wlasnie","szlachty","dwoch","wszystkich","litwie","gory","zeby","tych","srod","drzwi","sedziego","kazdy","stad","asesor","dobrze","wkolo","ktorej","ktorych","pierwszy","rejent","zosia","jedna","czlowiek","swiecie","przerwal","prawda","koniec","slychac","okiem","stary","wnet","nieraz","bron","chce","prawa","ksztalt","dalej","reku","serce","mogl","tylu","zamek","dwie","znak","zosi","byly","koncu","pewnie","chociaz","horeszkow","panow","czesto","slowo","wszak","wielka","widzac","nagle","wreszcie","bylem","usta","drzewa","trzy","wielkie","pole","naprzod","druga","czasem","takze","hrabiego","jacek","ciebie","zawolal","major","oczyma","mlodziez","wolna","mowiac","pomiedzy","soplica","glos","swej","wiesz","dworze","widzial","niegdys","twarz","dosyc","caly","wozny","dosc","kilka","azeby","wiem","nogi","swych","soba","zaczal","drugiej","taki","srodku","czym","maciej","zdrowie","calej","wiele","nasz","pani","jeneral","wiatr","ludzi","dawniej","biale","ktorym","wzrok","szlachcic","lata","oczu","rownie","wiwat","cicho","zwierza","soplicow","swiat","jestem","idzie","widzi","moskali","miala","wiedzial","jutro","cale","wola","panny","nieco","wolal","nalezy","taka","swoj","wzial","jezeli","nasze","swym","jednej","bracia","razy","panowie","bracie","protazy","drugi","biala","lubil","siedzi","wyszedl","siedzial","lasu","mowil","konia","stolu","maja","zbyt","ksiedza","prawo","niedzwiedz","ostatni","dabrowski","panu","strzelcy","sami","glupi","moja","jestes","dworu","dawno","blisko","podniosl","slowa","kobiety","droga","kaze","ktorego","goscie","bernardyn","moje","czasu","serca","wpol","chwile","kolo","kraju","czyli","drogi","prawie","dobrzynscy","tobie","niebo","obok","ktoz","spojrzal","dzieje","biezy","wojskiego","sedziemu","miejsce","dziecie","wielkiej"};
string Pru[300]={"wokulski","jest","pani","mnie","tylko","nawet","panna","moze","panie","jeszcze","wiec","ktory","sobie","jego","bardzo","izabela","albo","azeby","przez","wokulskiego","jezeli","kiedy","pana","tego","odparl","znowu","dzis","rubli","bylo","przed","rzekl","przy","chwili","czlowiek","ktora","mowil","wszystko","tysiecy","niej","bedzie","jednak","rzecki","jestem","baron","niego","mial","niech","siebie","gdzie","gdyby","ignacy","oczy","chce","potem","panu","ktore","wiem","myslal","mowi","lecz","panny","byla","jakby","kilka","dopiero","tych","teraz","taki","izabeli","pare","dobrze","domu","miedzy","reke","nich","spytal","wiecej","stach","dzien","sklepu","ochocki","zreszta","jakis","ktorym","baronowa","jeden","ktorych","nagle","drzwi","ludzi","sposob","troche","zawolal","ktorej","stary","wasowska","zawsze","choc","mozna","rzekla","drugi","kobieta","wlasnie","ktorzy","nigdy","prawie","starski","glowe","prosze","chyba","pokoju","rece","zaczal","wszyscy","moja","dodal","dalej","tomasz","zdawalo","pania","roku","taka","razy","stawska","przeciez","zaraz","szepnal","mogl","odpowiedzial","kobiety","tyle","tymczasem","swego","glowa","przecie","caly","bede","ksiaze","sklep","anizeli","musi","chwile","wszystkie","ludzie","pieniadze","mowie","czym","nareszcie","ojciec","czasu","czlowieka","jedna","trzy","trzeba","ktorego","mysli","szlangbaum","coraz","wokulskiemu","jakie","stawskiej","moge","mowila","prawda","zdaje","jaki","majatek","czego","cala","dlaczego","wtedy","pomyslal","masz","swoja","rzeczy","jakas","moje","pozniej","mysl","chcial","jestes","zrobil","mysle","prezesowa","szuman","poniewaz","takim","patrzac","okolo","chocby","miala","odezwal","jutro","nimi","list","doktor","naturalnie","sklepie","wiesz","panowie","dziesiec","wokulskim","swiat","sama","panne","zycie","razie","swoich","mruknal","dnia","takie","maja","alez","glosem","kazdy","zapytal","soba","lepiej","hrabina","adwokat","maruszewicz","jaka","glos","gdyz","takze","mlody","miec","ciagle","razem","pannie","czas","twarz","piec","swoje","wszedl","przynajmniej","boze","wzial","jedno","prawo","dlatego","robi","zawolala","byly","fotelu","swoim","geist","interes","znam","zeby","wszystkich","lecki","barona","hrabia","naprzod","naprawde","izabele","gdybym","baronowej","wowczas","zamiast","wreszcie","ktos","bylem","ulicy","swiecie","rozumiem","panem","zupelnie","serce","odpowiedziala","widzi","pierwszy","kilku","zrobic","jakies","wyszedl","pieniedzy","bowiem","wtracil","glowy","musze","widzial","robic","czul","piekna","ciebie","moim","jako","dwadziescia","skad","temu","mraczewski","nasz","takich","ojca","otoz","reka","spojrzal","wszystkim"};
string Sie[300]={"jego","jest","lecz","winicjusz","rzekl","mnie","tylko","ktory","jeszcze","przez","bylo","petroniusz","wiec","jednak","moze","sobie","ktora","przy","tego","poczal","chwili","nawet","panie","jakby","teraz","domu","ligia","przed","jesli","cezara","czym","ktorych","niego","cezar","winicjusza","ktore","bedzie","ligii","mogl","niej","oczy","mowil","albowiem","gdyby","wowczas","byla","nero","ludzi","ktorzy","jako","wreszcie","ktorego","miedzy","nich","ligie","gdzie","znow","wszystko","wszystkich","ktorej","odpowiedzial","ktorym","siebie","mial","tych","ludzie","chilo","zarazem","ciebie","glowe","wiecej","dlatego","rece","chcial","wsrod","coraz","mysl","niech","twarz","takze","tymczasem","wiem","bowiem","ursus","dzis","chwile","smierc","zycie","duszy","akte","czlowiek","nagle","miasta","wszystkie","petroniusza","nigdy","odrzekl","chce","potem","chrystusa","rzymie","jestem","dotad","rzym","chwila","glowy","smierci","nimi","jeden","moja","zycia","jedna","wszyscy","mowic","miasto","chrzescijan","milosc","swiat","czas","razem","chrystus","byly","dalej","rowniez","gdyz","cala","piotr","chrzescijanie","widzial","poczela","czasu","dopiero","wiesz","spytal","jaka","soba","niewolnikow","jakis","nikt","albo","rzymu","mozna","serce","tobie","twarzy","zawsze","apostol","wprawdzie","chocby","dobrze","trzeba","bogow","inni","caly","dzien","poczely","sama","eunice","innych","jakie","zawolal","nocy","milosci","mogla","cale","glosem","widok","bardziej","ancjum","wraz","zdawalo","glos","jakas","reke","glowa","slowa","czul","chwilami","masz","twoja","moje","poczeli","wobec","dlaczego","razie","musi","moge","kilka","rzeczy","dosc","takim","ziemi","zreszta","kazal","nerona","choc","pomponia","glowie","mysli","imie","toba","pomponii","piersi","atrium","nowe","zupelnie","bede","zwrocil","usta","niewolnicy","dusze","droga","lepiej","czesc","swiata","jakies","chilona","oczyma","czasem","inaczej","wprost","tygellinus","jakoz","podniosl","serca","ostrianum","kolo","bogowie","swiecie","aulusow","taka","widocznie","nastepnie","czego","zbyt","inne","winicjuszowi","drodze","mimo","woli","rzekla","przecie","tyle","jestes","pomyslal","wszystkim","nauka","poppea","pierwszy","jakkolwiek","obok","beda","dusza","zyciu","strony","chcac","jednej","widzialem","sposob","patrzec","wlasnie","miec","wiedzial","aulus","slow","widziec","slyszal","miescie","swej","przeciw","umial","znak","tlumy","ligio","procz","patrzyl","takie","istotnie","twoje","byli","niemal","jutro","stalo","apostola","mlody","mniej","dzieci","szczescie","jednakze","chilon","pawel","nieco","powodu","mowie","calym","zali","twarza","wiezienia","twoj","zaraz"};

int checkAmm(string &list){

	return 1;
}


/* pis.cpp */
int main(){
	/* ios_base::sync_with_stdio(0);
	cin.tie(0); */

	int T;
	string tekst;

	cin >> T;
	while (T--) {
		cin >> tekst;
		cout << tekst << '\n';

	}

} 
	
